명언 조회 api
team-homies/homis-step-of-liberty-history-service pull request #10
Opened 2024-06-02 07:03 UTC by SH2G

2024-06-02 08:00 UTC, nohhyeonjin requested changes
점점 발전하고있네용✨👍

2024-06-02 08:00 UTC, nohhyeonjin commented on app/api/dex/service/service.go
> +	return qow, err
flag, qow, rq 등 명확하지 않은 변수명은 지양하는게 좋아요!

2024-06-02 08:00 UTC, nohhyeonjin commented on app/api/dex/service/service.go
> +func (d *dexService) GetQuote() (res *resource.GetQuoteResponse, err error) {
API 실행하면 결과값이 null로 떨어지고 있어요!

2024-06-02 08:00 UTC, nohhyeonjin commented on app/api/dex/service/service.go
> +	if flag == 0 && weekDay == 1 {
flag와 weekDay를 둘 다 사용하는 이유를 잘 모르겠어요
weekDay가 월요일인지만 체크하면 되는거 아닐까요?

2024-06-02 08:00 UTC, nohhyeonjin commented on app/api/dex/service/service.go
> +	t := now.In(loc) // 그래서 서울 기준 UTC 세팅(+0900)
간단하게 줄일 수 있는 부분은 가독성을 위해 줄이는게 좋아요!
```
time.Now().In(loc)
```

2024-06-02 08:10 UTC, hawoond commented on app/api/dex/service/service.go
> +func (d *dexService) GetQuote() (res *resource.GetQuoteResponse, err error) {
qow가 nil일때의 예외 처리도 하면 좋겠네요

2024-06-02 08:39 UTC, hawoond commented on app/api/dex/service/service.go
> +	if flag == 0 && weekDay == 1 {
전날이 일요일이면서 오늘이 월요일의 첫번쨰 호출인지 체크하려고 조건을 건 것 같아요

2024-06-03 16:45 UTC, SH2G commented on app/api/dex/service/service.go
> +	return qow, err
@nohhyeonjin  넵 제가 없으면 유지보수 하기 어렵게 만들어서 이 프로젝트에 제가 없으면 안되게 만들려  했는데 들켜버렸네요😖  수정해보겠습니다!

2024-06-03 16:45 UTC, SH2G commented on app/api/dex/service/service.go
> +	t := now.In(loc) // 그래서 서울 기준 UTC 세팅(+0900)
오호 그렇네요 감사해요 수정 하겠습니다🙇‍♀️

2024-06-03 16:45 UTC, SH2G commented on app/api/dex/service/service.go
> +func (d *dexService) GetQuote() (res *resource.GetQuoteResponse, err error) {
넵

2024-06-03 17:06 UTC, merged